import Link from "next/link";

export default function Footer() {
  return (
    <footer className="border-t border-border bg-brand-dark">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          {/* Brand */}
          <div className="md:col-span-2">
            <div className="flex items-center gap-2 mb-4">
              <span className="text-teal text-lg">◆</span>
              <span className="text-lg font-bold font-heading tracking-tight">
                Legal<span className="text-teal">Forge</span>
              </span>
            </div>
            <p className="text-txt-secondary text-sm max-w-md mb-4 leading-relaxed">
              AI-powered legal document generation. Scan your website and get
              tailored Privacy Policies, Terms of Service, and Cookie Policies in
              seconds.
            </p>
            <p className="text-txt-muted text-xs">
              Built by{" "}
              <a
                href="https://automatik.studio"
                target="_blank"
                rel="noopener noreferrer"
                className="text-teal hover:text-teal-soft transition-colors duration-150"
              >
                Automatik.studio
              </a>
            </p>
          </div>

          {/* Product */}
          <div>
            <h4 className="font-heading font-semibold text-txt-primary mb-4 text-xs uppercase tracking-widest">
              Product
            </h4>
            <ul className="space-y-2.5">
              <li>
                <Link
                  href="/#features"
                  className="text-txt-secondary hover:text-txt-primary text-sm transition-colors duration-150"
                >
                  Features
                </Link>
              </li>
              <li>
                <Link
                  href="/#pricing"
                  className="text-txt-secondary hover:text-txt-primary text-sm transition-colors duration-150"
                >
                  Pricing
                </Link>
              </li>
              <li>
                <Link
                  href="/app"
                  className="text-txt-secondary hover:text-txt-primary text-sm transition-colors duration-150"
                >
                  Launch App
                </Link>
              </li>
            </ul>
          </div>

          {/* Legal */}
          <div>
            <h4 className="font-heading font-semibold text-txt-primary mb-4 text-xs uppercase tracking-widest">
              Legal
            </h4>
            <ul className="space-y-2.5">
              <li>
                <Link
                  href="/privacy"
                  className="text-txt-secondary hover:text-txt-primary text-sm transition-colors duration-150"
                >
                  Privacy Policy
                </Link>
              </li>
              <li>
                <Link
                  href="/terms"
                  className="text-txt-secondary hover:text-txt-primary text-sm transition-colors duration-150"
                >
                  Terms of Service
                </Link>
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-12 pt-8 border-t border-border flex flex-col sm:flex-row justify-between items-center gap-4">
          <p className="text-txt-muted text-sm">
            © {new Date().getFullYear()} LegalForge by Automatik Studio. All
            rights reserved.
          </p>
          <p className="text-txt-muted text-xs">
            Documents generated by AI. Always review with a legal professional.
          </p>
        </div>
      </div>
    </footer>
  );
}
