import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-brand-dark">
      <Navbar />
      <div className="pt-24 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl sm:text-4xl font-bold font-heading tracking-tight mb-2">
            Terms of <span className="text-teal">Service</span>
          </h1>
          <p className="text-txt-muted text-sm font-mono mb-10">
            Last updated: February 4, 2026
          </p>

          <div className="prose-legal">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using LegalForge (&quot;the Service&quot;), operated
              by Automatik Studio (&quot;we,&quot; &quot;our,&quot; or
              &quot;us&quot;), you agree to be bound by these Terms of Service. If
              you do not agree to these terms, please do not use our Service.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              LegalForge is an AI-powered tool that scans websites and generates
              legal documents including Privacy Policies, Terms of Service, and
              Cookie Policies. The Service uses artificial intelligence to analyze
              publicly accessible website content and create tailored legal
              documents based on detected technologies and integrations.
            </p>

            <h2>3. Important Disclaimer</h2>
            <p>
              <strong>
                LegalForge generates documents using AI and these documents are
                provided for informational purposes only. They do not constitute
                legal advice.
              </strong>{" "}
              We strongly recommend having all generated documents reviewed by a
              qualified legal professional before publishing them on your website.
              Automatik Studio is not a law firm and does not provide legal
              services.
            </p>

            <h2>4. User Responsibilities</h2>
            <p>When using our Service, you agree to:</p>
            <ul>
              <li>
                Only scan websites that you own or have authorization to scan
              </li>
              <li>
                Review and customize generated documents before publishing
              </li>
              <li>
                Not use the Service for any illegal or unauthorized purpose
              </li>
              <li>
                Not attempt to reverse engineer, decompile, or disassemble the
                Service
              </li>
              <li>
                Not use automated systems to access the Service in a manner that
                exceeds reasonable usage
              </li>
              <li>Provide accurate information when creating an account</li>
            </ul>

            <h2>5. Intellectual Property</h2>
            <p>
              The LegalForge platform, including its design, code, and branding, is
              the intellectual property of Automatik Studio. Legal documents
              generated by the Service are provided for your use and you may publish
              them on your website.
            </p>
            <p>
              Free tier documents include LegalForge branding. Paid plans allow
              removal of branding as specified in the plan features.
            </p>

            <h2>6. Subscription and Payments</h2>
            <ul>
              <li>
                <strong>Free Tier:</strong> Limited to 1 document with LegalForge
                branding. No payment required.
              </li>
              <li>
                <strong>Paid Plans:</strong> Subscription fees are billed monthly.
                Prices are as listed on our pricing page at the time of purchase.
              </li>
              <li>
                <strong>Cancellation:</strong> You may cancel your subscription at
                any time. Access continues until the end of the current billing
                period.
              </li>
              <li>
                <strong>Refunds:</strong> We offer a 14-day money-back guarantee for
                paid plans. Contact us within 14 days of your first payment for a
                full refund.
              </li>
            </ul>

            <h2>7. Service Availability</h2>
            <p>
              We strive to maintain high availability of our Service but do not
              guarantee uninterrupted access. The Service may be temporarily
              unavailable due to maintenance, updates, or circumstances beyond our
              control.
            </p>

            <h2>8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Automatik Studio shall not be
              liable for any indirect, incidental, special, consequential, or
              punitive damages, including but not limited to loss of profits, data,
              or business opportunities, arising from your use of the Service.
            </p>
            <p>
              We are not responsible for any legal consequences arising from the use
              of AI-generated documents without proper legal review. Users assume
              full responsibility for the legal documents they publish on their
              websites.
            </p>

            <h2>9. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Automatik Studio, its
              officers, directors, employees, and agents from any claims, damages,
              losses, or expenses arising from your use of the Service or violation
              of these Terms.
            </p>

            <h2>10. Third-Party Services</h2>
            <p>
              Our Service integrates with third-party providers including Anthropic
              (for AI generation) and Vercel (for hosting). Your use of these
              services is subject to their respective terms and policies.
            </p>

            <h2>11. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the
              Service at our sole discretion, without notice, for conduct that we
              believe violates these Terms or is harmful to other users, us, or
              third parties.
            </p>

            <h2>12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with
              applicable laws, without regard to conflict of law principles.
            </p>

            <h2>13. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will
              provide notice of significant changes by posting the updated Terms on
              our website. Your continued use of the Service after changes are
              posted constitutes acceptance of the modified Terms.
            </p>

            <h2>14. Contact Us</h2>
            <p>
              If you have questions about these Terms of Service, please contact us
              at{" "}
              <a href="mailto:automatikstudiomail@gmail.com">
                automatikstudiomail@gmail.com
              </a>
              .
            </p>
          </div>
        </div>
      </div>
      <Footer />
    </main>
  );
}
